# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='Rusty', max_length=250),
            preserve_default=False,
        ),
    ]
