# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20161022_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='Notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
