# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161017_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='customer',
            new_name='User',
        ),
    ]
