# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161018_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
