# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161024_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
