# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20161024_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('FR', 'Fridge'), ('RA', 'Rack'), ('AS', 'Ask')], default='Ask', max_length=20),
        ),
    ]
