# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20161025_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='OrderCompleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='basket',
            name='PlaceOrder',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Freezer', 'Freezer'), ('Cooler', 'Cooler'), ('Snack Rack', 'Snack Rack'), ('Pork Case', 'Pork Case'), ('Beef/Chicken Case', 'Beef/Chicken Case'), ('Cold Meat Case', 'Cold Meat Case'), ('Ask Employee', 'Ask Employee')], default='Ask Employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Poultry', 'Poultry'), ('Pork', 'Pork'), ('Deli', 'Deli'), ('Specialty Meats', 'Specialty Meats'), ('Groceries', 'Groceries')], default='Groceries', max_length=7),
        ),
    ]
