# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20160923_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='evenmore',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moreotherfeild',
        ),
        migrations.RemoveField(
            model_name='product',
            name='otherfeild',
        ),
        migrations.AddField(
            model_name='product',
            name='byPound',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('FRIDGE', 'Fridge'), ('RACK', 'Rack'), ('ASK', 'Ask')], default='ASK', max_length=20),
        ),
    ]
