# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20160927_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product',
        ),
        migrations.DeleteModel(
            name='basket',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
